server.name: kibana
server.host: "0.0.0.0"
elasticsearch.url: http://searchnode:9200

## Disable X-Pack
xpack.security.enabled: false
xpack.apm.ui.enabled: false
xpack.grokdebugger.enabled: false
xpack.searchprofiler.enabled: false
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.reporting.enabled: false
