---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "search"
network.host: 0.0.0.0
#
discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
#
### Disable X-Pack
## Disable X-Pack
#xpack.security.enabled: false
#xpack.monitoring.enabled: false
#xpack.ml.enabled: false
#xpack.watcher.enabled: false

search:
  remote:
    elastic1:
      seeds: elasticsearch1:9300
    elastic2:
      seeds: elasticsearch2:9300